[package]
name = "websocket-test"
version = "0.1.0"
authors = ["Peter Vivo <peter.vivo@appercell.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.11.1"
